# docker-compose -f compose.prod.yaml up --build
services:
  db:
    container_name: postgres_db
    image: postgres:15
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - ./backend/.env
    networks:
      - application
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 2s
      timeout: 2s
      retries: 5
  backend:
    container_name: analitika-backend
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    ports:
      - '4200:4200'
    networks:
      - application
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

networks:
  application:

volumes:
  db_data:
