# docker-compose -f compose.prod.yaml up --build
services:
  db:
    image: postgres:15
    restart: unless-stopped
    networks:
      - application
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 5s
      timeout: 2s
      retries: 20
  backend:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    networks:
      - application
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      target: production
      args:
        - VITE_SERVER_API=${VITE_SERVER_API}
    environment:
      - VITE_PORT=${VITE_PORT}
      - VITE_HOST=${VITE_HOST}
    restart: unless-stopped
    ports:
      - '${VITE_PORT}:80'
    networks:
      - application
    depends_on:
      backend:
        condition: service_started

networks:
  application:

volumes:
  db_data:
